name: Delete Old GitHub Pages
on:
  workflow_call:
concurrency:
  group: delete-old-pages
  cancel-in-progress: false
jobs:
  Clean:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Delete
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true
