name: Clean
on:
  workflow_dispatch:
    inputs:
      godot_version:
        default: '4.3'
permissions:
  contents: read
  pages: write
  id-token: write
  deployments: write
jobs:
  Clean:
    uses: ./.github/workflows/godot-build-and-deploy.yml
    with:
      godot_version: ${{ github.event.inputs.godot_version }}
