name: Clean
on:
  workflow_dispatch:
permissions:
  deployments: write
jobs:
  Clean:
    uses: ./.github/workflows/godot-build-and-deploy.yml
    with:
      godot_version: ${{ github.event.inputs.godot_version }}
