name: Delete Old GitHub Pages
on:
  workflow_call:
concurrency:
  group: delete-old-pages
  cancel-in-progress: false
permissions:
  deployments: write
jobs:
  Clean:
    runs-on: ubuntu-latest
    steps:
      - name: List Deployments
        run: gh deployment list --environment github-pages > deployments.txt
    # - name: Delete Old Deployments
    #   run: |
    #     while IFS= read -r line
    #     do
    #       deployment_id=$(echo $line | awk '{print $1}')
    #       deployment_date=$(echo $line | awk '{print $2}')
    #       if [ $(date -d $deployment_date +%s) -lt $(date -d '-30 days' +%s) ]; then
    #         gh deployment delete $deployment_id --environment github-pages
    #       fi
    #     done < deployments.txt
