name: Gobot
on:
  workflow_dispatch:
    inputs:
      godot-version:
        description: Godot Version
        default: '4.3'
        type: choice
        options:
          - '4.3'
          - '4.2'
          - '4.1'
      delete-old-pages:
        description: Delete Old Pages
        default: false
        type: boolean
permissions:
  pages: write
  id-token: write
  deployments: write
jobs:
  Gobot:
    uses: rakkarage/auto/.github/workflows/gobot.yml@main
    with:
      godot-version: ${{ github.event.inputs.godot-version }}
      delete-old-pages: ${{ github.event.inputs.delete-old-pages }}
