name: Godot Build and Deploy
on:
  workflow_dispatch:
    inputs:
      godot_version:
        description: Godot Version
        required: true
        default: '4.3'
concurrency:
  group: godot-build-and-deploy
  cancel-in-progress: false
permissions:
  contents: read
  pages: write
  id-token: write
env:
  GODOT_VERSION: ${{ github.event.inputs.godot_version }}
jobs:
  Setup: # cache godot and templates
    runs-on: ubuntu-latest
    steps:
      - name: Cache
        id: godot_cache
        uses: actions/cache@v4
        with:
          path: |
            ./godot
            ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable
          key: '${{ runner.os }}_Godot_${{ env.GODOT_VERSION }}'
      - name: Cache Godot
        if: steps.godot_cache.outputs.cache-hit != 'true'
        run: |
          curl -L -o godot.zip https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip
          unzip -q godot.zip
          mv Godot_v${GODOT_VERSION}-stable_linux.x86_64 godot
          chmod +x godot
      - name: Cache Godot Templates
        if: steps.godot_cache.outputs.cache-hit != 'true'
        run: |
          curl -L -o templates.zip https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_export_templates.tpz
          unzip -q templates.zip
          mkdir -v -p ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          mv templates/* ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
  Build: # build godot for 'all' platforms
    needs: Setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: Linux
            file: ${{ github.event.repository.name }}
            ext: x86_64
          - target: Web
            file: index
            ext: html
          - target: Windows
            file: ${{ github.event.repository.name }}
            ext: exe
          - target: macOS
            file: ${{ github.event.repository.name }}
            ext: zip
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Restore
        id: godot_cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ./godot
            ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable
          key: '${{ runner.os }}_Godot_${{ env.GODOT_VERSION }}'
      - name: Import
        run: ./godot --headless --verbose --editor --quit
      - name: Export
        run: |
          mkdir -v -p build/${{ matrix.target }}
          ./godot --headless --verbose --export-release '${{ matrix.target }}' build/${{ matrix.target }}/${{ matrix.file }}.${{ matrix.ext }}
      - name: Upload Web
        if: matrix.target == 'Web'
        uses: actions/upload-pages-artifact@v3
        with:
          name: '${{ github.event.repository.name }}_${{ matrix.target }}_Godot_${{ env.GODOT_VERSION }}'
          path: 'build/${{ matrix.target }}'
      - name: Upload Not Web
        if: matrix.target != 'Web'
        uses: actions/upload-artifact@v4
        with:
          name: '${{ github.event.repository.name }}_${{ matrix.target }}_Godot_${{ env.GODOT_VERSION }}'
          path: 'build/${{ matrix.target }}'
  Clean: # delete old github pages deployments
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Delete
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true
  Deploy: # deploy web artifact to github pages
    needs: [Build, Clean]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: '${{ steps.deployment.outputs.page_url }}'
    steps:
      - name: Configure
        uses: actions/configure-pages@v5
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: '${{ github.event.repository.name }}_Web_Godot_${{ env.GODOT_VERSION }}'
