name: Godot to GitHub Pages
on:
  workflow_dispatch:
concurrency:
  group: pages
  cancel-in-progress: false
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: 'barichello/godot-ci:4.3'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Export
        run: |
          mkdir -v -p build/web
          godot --headless --verbose --editor --quit
          godot --headless --verbose --export-release "Web" build/web/index.html
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: build/web
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: '${{ steps.deployment.outputs.page_url }}'
    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: web
          path: build/web
      - name: Setup
        uses: actions/configure-pages@v2
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
