name: Trigger Delete Old GitHub Pages
on:
  workflow_dispatch:
permissions:
  deployments: write
jobs:
  trigger-delete-old-github-pages:
    uses: rakkarage/gflop/.github/workflows/delete-old-github-pages.yml@main
