name: Trigger Godot Build and Deploy
on:
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  Trigger:
    uses: rakkarage/auto/.github/workflows/godot-build-and-deploy.yml@main
